changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔄 Refactoring
      labels:
        - refactor
        - refactoring
    - title: 🚨 Tests
      labels:
        - test
        - tests
    - title: ⚙️ Chore
      labels:
        - chore
        - ci
        - build
